apiVersion: 1

datasources:
  - name: JMeter InfluxDB
    uid: jmeter-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: jmeter
    user: ${INFLUXDB_USER}
    secureJsonData:
      password: ${INFLUXDB_USER_PASSWORD}
    isDefault: true
