{
 "title": "JMX Exporter JVM",
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "project_id",
    "query": "label_values(jvm_memory_bytes_used, project_id)"
   },
   {
    "name": "target_id",
    "query": "label_values(jvm_memory_bytes_used{project_id=\"$project_id\"}, target_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",project_id=\"$project_id\",target_id=~\"$target_id\"}"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{project_id=\"$project_id\",target_id=~\"$target_id\"}[1m])"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "jvm_threads_current{project_id=\"$project_id\",target_id=~\"$target_id\"}"
    }
   ]
  },
  {
   "title": "Class Loading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "jvm_classes_loaded{project_id=\"$project_id\",target_id=~\"$target_id\"}"
    }
   ]
  }
 ]
}